### ISSUE TITLE
LDAP authentication failing

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#1]
I have followed the instructions provided in below link to setup BuildOn 
https://onedevops.atlassian.net/wiki/spaces/OB/pages/11108353/Installation+of+BuildOn

I have enabled LDAP for authentication. But when I try to login to the buildon ui the authentication is failing with "invalid credentials" and shows below error on buildonui.log 

> 07:26:25.663 [http-nio-8443-exec-9] DEBUG c.c.b.domain.LDAPAuthentication - javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
> 07:26:25.663 [http-nio-8443-exec-9] DEBUG c.c.b.domain.LDAPAuthentication - javax.naming.NotContextException: Not an instance of DirContext

My LDAP settings are 

> #LDAP
> ldap.server=ldap://ldapserver:389
> ldap.isLDAP=true
> ldap.user=Manager
> ldap.password=pass
> ldap.searchbase=DC=maxcrc,DC=com
> ldap.distributionlist=

I'm trying to login with e-mail id in build on ui. Is there any configurations I have missed out? Please help

**Comment by MalarvizhiChandramohan** [comment]
Its a openLDAP issue .We are working on this .This fix will be available  in couple of days .

**Comment by smartdevops** [comment]
After few ldap configuration code changes I'm able to login the  buildon UI succcesfully.

![image](https://user-images.githubusercontent.com/33824782/33198814-42d7f50e-d113-11e7-94a7-3c43281b44da.png)

Now on the buildon Tab the  repository list is empty.

![image](https://user-images.githubusercontent.com/33824782/33198891-bbbe8884-d113-11e7-8f33-abbd5045f5a0.png)

Here's the buildonui.log details

> 07:05:14.602 [http-nio-8443-exec-6] DEBUG c.m.v.c.i.C3P0PooledConnectionPoolManager - Created new pool for auth, username (masked): 'po******'.
> 07:05:14.603 [http-nio-8443-exec-6] DEBUG c.m.v.resourcepool.BasicResourcePool - acquire test -- pool size: 0; target_pool_size: 1; desired target? 1
> 07:05:14.608 [http-nio-8443-exec-6] DEBUG c.m.v.resourcepool.BasicResourcePool - awaitAvailable(): [unknown]
> 07:05:15.380 [http-nio-8443-exec-6] DEBUG c.m.v2.c3p0.impl.NewProxyConnection - com.mchange.v2.c3p0.impl.NewProxyConnection@60b6b8cc [wrapping: org.postgresql.jdbc.PgConnection@4bef1fa3]: close() called more than once.
> 07:05:15.389 [http-nio-8443-exec-6] INFO  c.c.b.c.AuthenticationWebController - 271 doPost encrypt value:awscloud
> 07:05:15.390 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - setting ldap context
> 07:05:15.400 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - 252 ou=people (mail=845693@example.com)
> 07:05:15.402 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - 259 results > 1
> 07:05:15.403 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication -  271 empID:845693
> 07:05:15.403 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - setting ldap context
> 07:05:15.412 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - 319 user 845693 is valid
> 07:05:15.412 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - 275 Inside valid
> 07:05:15.412 [http-nio-8443-exec-6] INFO  c.c.b.domain.LDAPAuthentication - 279 845693 845693@example.com valid
> 07:05:15.608 [http-nio-8443-exec-5] INFO  c.c.b.domain.LDAPAuthentication - setting ldap context
> 07:05:15.614 [http-nio-8443-exec-5] DEBUG c.c.buildon.dao.BuildOnDAOImpl - getscm details with userid and type start
> 07:05:18.806 [http-nio-8443-exec-1] INFO  c.c.b.domain.LDAPAuthentication - setting ldap context
> 07:05:18.869 [pool-2-thread-1] INFO  c.c.buildon.dao.BuildOnDAOImpl - getBuildtrends methods start.
> 07:05:18.876 [pool-2-thread-1] DEBUG c.c.buildon.dao.BuildOnDAOImpl - Create Connection
> 07:05:18.878 [pool-2-thread-3] DEBUG c.c.buildon.dao.BuildOnDAOImpl - getLatestbuild methods start.
> 07:05:18.878 [pool-2-thread-3] DEBUG c.c.buildon.dao.BuildOnDAOImpl - Create Connection
> 07:05:18.879 [pool-2-thread-2] INFO  c.c.buildon.dao.BuildOnDAOImpl - getProjectwiseBuild methods start.
> 07:05:18.879 [pool-2-thread-2] DEBUG c.c.buildon.dao.BuildOnDAOImpl - Create Connection
> 07:05:18.882 [pool-2-thread-4] DEBUG c.c.buildon.dao.BuildOnDAOImpl - getCompareBuild methods start.
> 07:05:18.882 [pool-2-thread-4] DEBUG c.c.buildon.dao.BuildOnDAOImpl - Create Connection
> 07:05:22.412 [DefaultQuartzScheduler_QuartzSchedulerThread] DEBUG o.quartz.core.QuartzSchedulerThread - batch acquisition of 0 triggers
> 

Any clues on this issue ?

**Comment by JeyanthiBalakrishnan** [comment]
In SCM page, keep the "Set as Default" to ON. One project with "Set as Default" is mandatory to load repository details in BuildOn page.

**Comment by JeyanthiBalakrishnan** [comment]
Closing the issue as the reported ldap issue is fixed.
