### ISSUE TITLE
Bitbucket Test connection failing

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#10]
Hi,

I' ve setup Buildon with below configuration

Operating System: Centos 7.3
Tomcat :  8.0.39
Buildon:  1.2.2
Python:  2.7.5
K8S: v1.8.1
Postgres: v9.5.10

I'm using Bitbucket 5.7 as SCM tool with valid personal access token and getting exception on Test Connection 

![image](https://user-images.githubusercontent.com/33824782/35899567-1eae000e-0bf3-11e8-9489-75c1f8d44401.png)

DEBUG c.c.buildon.domain.GitOperations - org.eclipse.jgit.api.errors.TransportException: http://buildon@10.0.0.0:7990/scm/seal/samplestudentproject.git: not authorized

Buildon log files attached.
[buildon_rollingfile.2018-02-07.0.log](https://github.com/CognizantOneDevOps/BuildOn/files/1701836/buildon_rollingfile.2018-02-07.0.log)

Any clue on this issue ?

**Comment by SowmiyaRanganathan** [comment]
@smartdevops 
BitBucket, GitHub and GitLab commit payload are different. As of now we have support for SCMs GitHub and GitLab. 

BuildOn for BitBucket will be released in the future.

**Comment by SowmiyaRanganathan** [comment]
Additionally, SCM url need not have the "username@"  (say, https://username@domain:port) since we pass the OAuth token for access verification.

**Comment by smartdevops** [comment]
@SowmiyaRanganathan 
Many thanks for information any tentative release date for this Bitbucket SCM feature ?

**Comment by jeydevops** [comment]
You may expect in next release which is expected to happen in couple of weeks time.

**Comment by JeyanthiBalakrishnan** [comment]
You may expect in next release which is expected to happen in couple of weeks time.

**Comment by smartdevops** [comment]
@JeyanthiBalakrishnan 
Thanks for information

**Comment by JeyanthiBalakrishnan** [comment]
@smartdevops 
Buildon for atlassian bitbucket has been released in v2.0. Please refer release notes.
https://onedevops.atlassian.net/wiki/spaces/OB/pages/24707608/Release+Notes
