### ISSUE TITLE
openldap login fails

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#2]
I have tried the latest code v1.2 with openLDAP configurations. I'm not able to login to the UI. Here's my ldap settings.

> #LDAP
> ldap.server=ldap://ldapserver:389/
> #For openLDAP anonymous user  ldap.user and ldap.password set to empty.
> #For LDAP set values - ldap.user and ldap.password
> ldap.user=
> ldap.password=
> ldap.searchbase=dc=maxcrc,dc=com
> ldap.distributionlist=
> #For ldap isLDAP set to true
> ldap.isLDAP=true
> #For openldap isopenLDAP set to true
> ldap.isopenLDAP=true
> 

This is the error in tomcat logs.
> 
> 24-Nov-2017 09:57:47.950 SEVERE [http-nio-8443-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [com.cognizant.buildon.controller.AuthenticationWebController] in context with path [/buildon] threw exception
>  java.lang.NullPointerException
>         at com.cognizant.buildon.domain.LDAPAuthentication.getEmpId(LDAPAuthentication.java:294)
>         at com.cognizant.buildon.controller.AuthenticationWebController.doPost(AuthenticationWebController.java:289)
> 

Any suggestions please?

**Comment by JeyanthiBalakrishnan** [comment]
Please note that you should either use isLDAP or isopenLDAP flag. As you want to use isopenLDAP(true), ldap.user and ldap.password should be empty. isLDAP should set to false. If you enable isLDAP to true then you should provide values to ldap.user and ldap.password. Also, note that ldap.user is filtered with emp.id as the key. We are working on it to integrate with other unique key factor like email..

Please try with below configuration for your current issue.
#LDAP
ldap.server=ldap://ldapserver:389/
#For openLDAP anonymous user ldap.user and ldap.password set to empty.
#For LDAP set values - ldap.user and ldap.password
ldap.user=
ldap.password=
ldap.searchbase=dc=maxcrc,dc=com
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=false
#For openldap isopenLDAP set to true
ldap.isopenLDAP=true

**Comment by smartdevops** [comment]
Jeyanthi,
Thanks for your response. I have tried with the mentioned changes. Login with e-mail id is failing again. Please update once you have fix for this.

**Comment by JeyanthiBalakrishnan** [comment]
ok. Meanwhile, you can use release v1.1 and use your code changes as you specified earlier to move forward.

**Comment by smartdevops** [comment]
Jeyanthi,

I have configured the SCM with v1.1 and tried running  buildon. But getting below errors on buildonui.log


> 12:33:22.287 [http-nio-8443-exec-1] DEBUG com.mchange.v2.sql.SqlUtils - Attempted to convert SQLException to SQLException. Leaving it alone. [SQLState: 42883; errorCode: 0]
> org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = bytea
>   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
>   Position: 249

> 12:33:22.327 [http-nio-8443-exec-6] DEBUG c.m.v.c.impl.DefaultConnectionTester - Testing a Connection in response to an Exception:
> org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = bytea
>   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
>   Position: 748
> 12:33:22.849 [http-nio-8443-exec-12] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
> 12:33:22.849 [http-nio-8443-exec-12] DEBUG io.fabric8.kubernetes.client.Config - Found for Kubernetes config at: [/home/ubuntu/admin.conf].
> 12:33:22.861 [http-nio-8443-exec-12] DEBUG c.c.buildon.domain.GitOperations - getDBServiceUpdate:null:null:null
> 12:33:22.861 [http-nio-8443-exec-12] DEBUG c.c.buildon.domain.GitOperations - fileName...null/Jenkinsfilecommitid...null
> 12:33:22.861 [http-nio-8443-exec-12] DEBUG c.c.buildon.domain.GitOperations - java.io.FileNotFoundException: null/Jenkinsfile (No such file or directory)

**Comment by jeydevops** [comment]
Please find the config details for both openLDAP anonymous and non-anonymous users.

1). **For openLDAP anonymous user. openLDAP must be configured to accept anonymous user access.**

#LDAP
ldap.server=ldap://ldapserver:389/
#For openLDAP anonymous user ldap.user and ldap.password set to empty.
#For LDAP set values - ldap.user and ldap.password
ldap.user=
ldap.password=
ldap.searchbase=dc=maxcrc,dc=com
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=true
#For openldap isopenLDAP set to true
ldap.isopenLDAP=true

**2). For openLDAP non-anonymous user.**

#LDAP
ldap.server=ldap://ldapserver:389/
#For openLDAP anonymous user ldap.user and ldap.password set to empty.
#For LDAP set values - ldap.user and ldap.password
ldap.user=<emp.id>
ldap.password=<password>
ldap.searchbase=dc=maxcrc,dc=com
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=true
#For openldap isopenLDAP set to true
ldap.isopenLDAP=true


Please update your configuration and let us know if an issue still persists.

**Comment by JeyanthiBalakrishnan** [comment]
Please find the config details for both openLDAP anonymous and non-anonymous users.

1). For openLDAP anonymous user. openLDAP must be configured to accept anonymous user access.

#LDAP
ldap.server=ldap://ldapserver:389/
#For openLDAP anonymous user ldap.user and ldap.password set to empty.
#For LDAP set values - ldap.user and ldap.password
ldap.user=
ldap.password=
ldap.searchbase=dc=maxcrc,dc=com
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=true
#For openldap isopenLDAP set to true
ldap.isopenLDAP=true

2). For openLDAP non-anonymous user.

#LDAP
ldap.server=ldap://ldapserver:389/
#For openLDAP anonymous user ldap.user and ldap.password set to empty.
#For LDAP set values - ldap.user and ldap.password
ldap.user=<emp.id>
ldap.password=
ldap.searchbase=dc=maxcrc,dc=com
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=true
#For openldap isopenLDAP set to true
ldap.isopenLDAP=true

Please update your configuration and let us know.

**Comment by smartdevops** [comment]
Hi Jeyanthi,

For openLDAP non-anonymous user I'm getting below errror

#LDAP

> 
> ldap.server=ldap://ldapserver:389
> #For openLDAP anonymous user  ldap.user and ldap.password set to empty.
> #For LDAP set values - ldap.user and ldap.password
> ldap.user=845693
> ldap.password=
> ldap.searchbase=dc=maxcrc,dc=com
> ldap.distributionlist=
> #For ldap isLDAP set to true
> ldap.isLDAP=true
> #For openldap isopenLDAP set to true
> ldap.isopenLDAP=true
> 
> 

> 27-Nov-2017 11:01:31.497 SEVERE [http-nio-8443-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [com.cognizant.buildon.controller.AuthenticationWebController] in context with path [/buildon] threw exception
>  java.lang.NullPointerException
>         at com.cognizant.buildon.domain.LDAPAuthentication.getEmpId(LDAPAuthentication.java:294)
>         at com.cognizant.buildon.controller.AuthenticationWebController.doPost(AuthenticationWebController.java:289)

**Comment by JeyanthiBalakrishnan** [comment]
Buildon latest version 1.2.1  fixed the openldap non-anonymous user access issue.

**Comment by JeyanthiBalakrishnan** [comment]
Closing the issue. Fix given in BuildOn v1.2.1
