### ISSUE TITLE
Buildon is failing

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#4]
Team,
I have installed buildon UI v1.2 with local DB authentication.
I'm using the latest image "devopsbasservice/buildonframework:buildonJenkinsfile2.0" in Jenkinsfile.
I'm able to configure SCM and buildon is failing with few errors. Attaching the buildonui & framework log for your reference 
[buildon_rollingfile.2017-11-28.0.log](https://github.com/CognizantOneDevOps/BuildOn/files/1508728/buildon_rollingfile.2017-11-28.0.log)

[framework.log](https://github.com/CognizantOneDevOps/BuildOn/files/1508729/framework.log)

**Comment by JeyanthiBalakrishnan** [comment]
Please provide pod logs "kubectl logs pod-name"

**Comment by smartdevops** [comment]
kubectl logs buildon-65xlyxk
Error from server (NotFound): pods "buildon-65xlyxk" not found

**Comment by JeyanthiBalakrishnan** [comment]
kubectl run '65xlyxk' -i --tty --rm --restart=Never --image='devopsbasservice/buildonframework:buildonJenkinsfile2.0' --env=commitID='65xlyxk',branchName='master',gitURL='https://github.com/smartdevops/SampleStudentProject.git',KUBEMASTER='10.0.0.94',UPLOADPORT='5000'


please run this command from your kubernette master and pull the console log from there. It will start with jenkins startup.

**Comment by smartdevops** [comment]
Jeyanthi,

Here's the results of the command

>  kubectl run '65xlyxk' -i --tty --rm --restart=Never --image='devopsbasservice/buildonframework:buildonJenkinsfile2.0' --env=commitID='65xlyxk',branchName='master',gitURL='https://github.com/smartdevops/SampleStudentProject.git',KUBEMASTER='10.0.0.94',UPLOADPORT='5000'
> /opt/git-askpassword.sh
> Git URL:
> 
> Branch name:
> 
> CommitID:
> 65xlyxk,branchName=master,gitURL=https://github.com/smartdevops/SampleStudentProject.git,KUBEMASTER=10.0.0.94,UPLOADPORT=5000
> mv: cannot move '/var/jenkins/jobs/jenkinsfileJob' to '/var/jenkins/jobs/65xlyxk,branchName=master,gitURL=https://github.com/smartdevops/SampleStudentProject.git,KUBEMASTER=10.0.0.94,UPLOADPORT=5000': No such file or directory
> pod default/65xlyxk terminated (Error)
>

**Comment by JeyanthiBalakrishnan** [comment]
Please check your mounted volume and RAM heap memory in Kubernete instances. Specified image is trying to execute its Dockerfile steps in the pod(contianer) in Slave machine. Looks like there is not much storage or heap space. Please check "df -h" and "free -h" in all your kube instances (master and slaves). Hope you are using the recommended hardware configuration. I tried to replicate the issue in our kube instances. I am able to spawn the pod for the specified image.

**Comment by smartdevops** [comment]
Jeyanthi,

There is enough memory and disk space on the slave node and master node.

>  free -h
>               total        used        free      shared  buff/cache   available
> Mem:           3.9G        320M        548M        309M        3.0G        2.9G
> Swap:            0B          0B          0B
> 
> 
>  df -H
> Filesystem      Size  Used Avail Use% Mounted on
> udev            2.1G     0  2.1G   0% /dev
> tmpfs           415M   43M  372M  11% /run
> /dev/xvda1       52G  5.4G   47G  11% /

**Comment by JeyanthiBalakrishnan** [comment]
Tried to replicate the kubectl run in my environment with ubuntu as base OS platform, it is working fine. Looks like, source directory not found to do mv command as per base image entry point. source directory will be created as per base image Dockerfile. Are you using ubuntu ?

**Comment by smartdevops** [comment]
Jeyanthi,
Yes I'm using ubuntu instance in AWS.

**Comment by JeyanthiBalakrishnan** [comment]
As per your logs, Git URL, Branch name and CommitID values are wrong. These values are extracted using buildon.py As per log, commitID is "65xlyxk,branchName=master,gitURL=https://github.com/smartdevops/SampleStudentProject.git,KUBEMASTER=10.0.0.94,UPLOADPORT=5000". 

It is supposed to be "65xlyxk"

Log:
Git URL:

Branch name:

CommitID:
65xlyxk,branchName=master,gitURL=https://github.com/smartdevops/SampleStudentProject.git,KUBEMASTER=10.0.0.94,UPLOADPORT=5000

Please share your buildon.py and the python version. I hope ubuntu 16.04 xenial.

**Comment by smartdevops** [comment]
Jeyanthi,

Please find the requested details below
1) OS: Ubuntu 16.04.3 LTS
2) Python version: Python 2.7.12
3) buildon.py
```
#!/usr/bin/env python
import json, os, wget , glob
import docker
from docker.errors import DockerException
from pprint import pprint
import subprocess
#from scalr.client import ScalrApiClient
#import scalr
import pg8000
from io import BytesIO
from docker import APIClient
import datetime
import sys
import re
import string
import shutil
import configparser

class BuildOn(object):
    def __init__(self, data):
        ##Fetch server details and ports from properties file
        data = json.loads(data)
        config = configparser.ConfigParser()
        config.sections()
        config.read('buildon.properties')
        config.sections()
        'server' in config
        self.host_ip=config['server']['kubemaster_ip']
        self.upload_port=config['server']['framework_port']
        self.gitlabtoken=config['server']['serviceaccount']
        print "Printing Payload Data ......"
        print data

        ##Extract Payload data from respective Source Code Repository.Here "head_commit" is the key word
        ##which differs between GitLab and GitHub Payload content.Using this payload extraction is done.
        if  'head_commit' not in data:
                print "GitLab Commit"
                self.commitid = format(data['commits'][0]['id'])[0:7]
                self.unique = format(data['ref'])
                self.tuid = self.unique.split("/")[2]
                self.tagid = self.tuid + self.commitid
                self.uid = "buildon-" + self.commitid
                self.repo_name = format(data['repository']['name'])
                self.buildpath = '/root/buildlog/'+ self.commitid
                self.scmuser = format(data['commits'][0]['author']['email'])
                self.webhookcheck = format(data['repository']['git_http_url'])
                self.httpurl = format(data['project']['http_url'])
                self.repohttpurl = self.httpurl.replace(".git","")
                self.jenkinsfileURL=self.repohttpurl + "/" + "raw" + "/" + self.tuid + "/" + "Jenkinsfile?private_token="+self.gitlabtoken

                print "Printing Paylaod data...***"
                print "CommitID..."+ self.commitid
                print "UID..."+ self.uid
                print "Branch..." + self.tuid
                print "repo_name..."+ self.repo_name
                print "buildpath" + self.buildpath
                print "scmuser..."+ self.scmuser
                print "webhookcheck..." + self.webhookcheck
                print "httpurl ..." + self.httpurl
                print "repohttpurl..." + self.repohttpurl
                print "jenkisnfileURL..." + self.jenkinsfileURL
        else:
                print "GitHub commit"
                print "Printing data"
                print data
                self.commitid = format(data['commits'][0]['id'])[0:7]
                self.unique = format(data['ref'])
                self.tuid = self.unique.split("/")[2]
                self.tagid = self.tuid + self.commitid
                self.uid = "buildon-" + self.commitid
                self.repo_fullName = format(data['repository']['full_name'])
                self.repo_name = format(data['repository']['name'])
                self.buildpath = '/root/buildlog/'+ self.commitid
                self.scmuser = format(data['commits'][0]['author']['email'])
                self.webhookcheck = format(data['repository']['git_url'])
                self.httpurl = format(data['repository']['clone_url'])
                self.repohttpurl = self.httpurl.replace(".git","")
                #self.jenkinsfileURL="https://raw.githubusercontent.com/"+self.repo_fullName + "/" + self.tuid + "/" + "webapp/Jenkinsfile"
                self.jenkinsfileURL="https://raw.githubusercontent.com/"+self.repo_fullName + "/" + self.tuid + "/" + "Jenkinsfile"

                print "Printing Paylaod data...***"
                print "CommitID..."+ self.commitid
                print "UID..."+ self.uid
                print "Branch..." + self.tuid
                print "repo_name..."+ self.repo_name
                print "repo_fullname..."+ self.repo_fullName
                print "buildpath" + self.buildpath
                print "scmuser..."+ self.scmuser
                print "webhookcheck..." + self.webhookcheck
                print "httpurl ..." + self.httpurl
                print "repohttpurl..." + self.repohttpurl
                print "jenkisnfileURL..." + self.jenkinsfileURL

	os.environ['commit_id'] = self.commitid
        os.environ['repoName'] = self.repo_name
        os.environ['branchName'] = self.tuid

    def derbydbinsert(self):
	    print "Inside self.derbydbinsert"
            now = datetime.datetime.now()
            self.start_timestamp = now.strftime("%Y-%m-%d %H:%M:%S")
            self.start_date = now.strftime("%Y-%m-%d")
	    print self.scmuser
            print self.tuid
            print self.repo_name
	    result = ''
            try:
	    	##Check if WebHook is ON/OFF. If OFF exit the execution.Exit only if commit is from GitLab checkin and Webhook is OFF.
	    	con = pg8000.connect(user="postgres", password="admin123")
	    	cur = con.cursor()
	    	cur.execute("select webhook from buildon_preferences where email='"+self.scmuser+"' and REPOSITORY='"+self.repo_name+"'")
            	#resulttemp=subprocess.check_output(['java', '-jar', 'derbyPreferencesHook.jar',self.scmuser,self.repo_name])
            	#result = resulttemp.strip()
	    	for row in cur:
		    result =  row[0]
	    except Exception as e:
		print e
		print 'Preference Error'
	    finally:
	    	con.close()
	    print "self.webhookcheck: " + self.webhookcheck
            if ( result == 0 and self.webhookcheck != "" and 'BOT' not in self.webhookcheck ):  ##Exits without BuildOn flow if webhook is turnedd off when committign code directly to SCM
		print 'WebHook is off'
                return 0

            if ( self.webhookcheck != "" ):
            	if ('BOT' in self.webhookcheck):
			trigger_from="BOT"
	        else:
			trigger_from="FRAMEWORK" 
	    else:
		trigger_from="UI"
	    print trigger_from
	    print 'trigger_from'
            file = open(self.buildpath+"/Jenkinsfile").read().splitlines()
            try:
                for index, line in enumerate(file):
                        #if "stage" in line:
			if "stage ('" in line or "stage('" in line:
                                #line_temp = line
                                #start = line_temp.index("'") + len("'")
                                #end = line_temp.index( "'", start )
                                #ci_jobname= line_temp[start:end]
				ci_jobname =line.split("'")[1]
                                print ci_jobname
				con = pg8000.connect(user="postgres", password="admin123")
				cur = con.cursor()
				est_dur = ''
				cur.execute("select jobname from buildon_reports where STATUS='SUCCESS' and BRANCH='"+self.tuid+"' group by jobname;")
                                if len(list(cur)) > 0:
                                        cur.execute("select avg(d) as DURATION from (select sum(DURATION) as d from buildon_reports where STATUS='SUCCESS' and BRANCH='"+self.tuid+"' group by jobname) as tmp;")
                                        for row in cur:
                                                minutes = int(row[0]/ 60000)
                                                minutes1 = row[0] % 60000
                                                seconds = int(minutes1 / 1000)
                                                est_dur = str(minutes) + "Mins " + str(seconds) + "Sec"
				cur.execute("insert into buildon_reports (BRANCH,COMMITID,JOBNAME,PROJECT,SCMUSER,STARTDATE,START_TIMESTAMP,CI_JOBNAME,STATUS,ESTIMATED_DURATION,TRIGGER_FROM)  values ('"+self.tuid+"','"+self.commitid+"','"+self.uid+"','"+self.repo_name+"','"+self.scmuser+"','"+self.start_date+"','"+self.start_timestamp+"','"+ci_jobname+"','NOTSTARTED','"+est_dur+"','"+trigger_from+"')")
				con.commit()
				con.close()
				#subprocess.call(['java', '-jar', 'derbyInsert.jar',self.tuid,self.commit_id,self.uid,self.repo_name,self.scmuser,self.start_date,self.start_timestamp,ci_jobname,'NOTSTARTED',trigger_from],stdout=open('/root/buildlog/'+self.commit_id+'/other.log', 'a'),stderr=open('/root/buildlog/'+self.commit_id+'/other.log', 'a'))
            except Exception as e:
		print 'Insert Error Occurs'
                print e

    def setup(self, data):
        if not os.path.exists(self.buildpath):
            os.makedirs(self.buildpath)
            try:
                        wget.download(self.jenkinsfileURL, out=self.buildpath+"/Jenkinsfile")
            except Exception as e:
                        print "Error in downloading files from SCM - Jenkinsfile or fetch image from Jenkinsfile"
	    try:
                 file = open(self.buildpath+"/Jenkinsfile").read().splitlines()
                 for index, line in enumerate(file):
                        if "env.dockerimagename" in line:
                                line_temp = line
                                imagename_temp=line_temp.split("=")[1]
                                imagename=imagename_temp.strip()
                                print "Docker Image Name: " + imagename
	    except Exception as e:
               	print e
            try:
                #self.replacestring(self.buiildpath + "/Jenkinsfile", "<appndid>", self.uid)
		##DerbyDB insert function call 
		hook = self.derbydbinsert()
                if ( hook == 0 ):
                    return 0
                subprocess.Popen(['kubectl run '+ self.uid +' -i --tty --rm --restart=Never --image='+imagename+ ' --env="commitID='+self.uid+',branchName='+self.tuid+',gitURL='+self.httpurl+',KUBEMASTER='+self.host_ip+',UPLOADPORT='+self.upload_port+'"'], shell=True) #, stdout=open('/root/buildlog/'+self.commit_id+'/other.log', 'a'),stderr=open('/root/buildlog/'+self.commit_id+'/other.log', 'a'))
            except NameError as ne:
		print ne
                raise BuildOn(
                    "Error in replacing <appndid> in Jenkinsfile"
                )

    @staticmethod
    def replacestring (filepath, orgstring, replacestring):
        if os.path.isfile(filepath):
            filehandle = open(filepath, "r+")
            lines = filehandle.read()
            lines = lines.replace(orgstring, replacestring)
            filehandle.close()
            filehandle = open(filepath, "w")
            filehandle.write(lines)
            filehandle.close()
        else:
            print('File not found{}'.filepath)

```

**Comment by JeyanthiBalakrishnan** [comment]
Framework looks OK. Then need to look into an application code which sends the payload using the callBuildOn in GitOperations.  Also, try setting the "hibernate.jdbc.lob.non_contextual_creation=true" in persistence.xml for DB exception in application log "java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented". 

Add logger for github json payload in callBuildOn if required for further troubleshooting.

Please validate the buildon.properties located in "src/main/resources/buildon.properties" as shown below.

#Property File
postgresql.driver=org.postgresql.Driver
postgresql.url=jdbc:postgresql://postgres-server-ip:-5432/postgres
postgresql.username=postgresdb-user
postgresql.password=postgresdb-password

#Kubernetes 
python.url=http://xx.xx.xx.xx:5000
#kube API URL
kubernetes.url=https://xxx.xxx.xx.xx:6443

#kubernetes logs
kubernetes.namespace=default
kubernetes.podport=8080
kubernetes.logbasepath=/root/buildlog/

#Scheduler Mandatory fields
#Seconds Minutes Hours Day-of-Month Month Day-of-Week
#Pay attention to the effects of '?' and '*' in the day-of-week and day-of-month fields
#Midnight execution
#cronschedule=0 0 0 * * ?
cronschedule=59 59 23 * * ?

#Below config can be used for login with DB table
#LDAP
ldap.server=
#For openLDAP anonymous user  ldap.user and ldap.password set to empty. 
#For LDAP set values - ldap.user and ldap.password
ldap.user=
ldap.password=
ldap.searchbase=
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=false
#For openldap isopenLDAP set to true
ldap.isopenLDAP=false

**Comment by smartdevops** [comment]
Jeyanthi,

Still the same issue on python framework. I'm running tomcat as ubuntu user and python framework as root user. Will it be a problem ?

> [2017-11-29 10:29:51 +0000] [7708] [INFO] Starting gunicorn 19.4.5
> [2017-11-29 10:29:51 +0000] [7708] [INFO] Listening at: http://0.0.0.0:5000 (7708)
> [2017-11-29 10:29:51 +0000] [7708] [INFO] Using worker: gevent
> [2017-11-29 10:29:51 +0000] [7713] [INFO] Booting worker with pid: 7713
> [2017-11-29 10:29:51 +0000] [7714] [INFO] Booting worker with pid: 7714
> Inside DerbyUpdate.py
> w7l0cav
> SampleStudentProjectmaster
> Traceback (most recent call last):
>   File "/home/ubuntu/BuildOn/dbupdate.py", line 23, in <module>
>     for i in resp_dict['items']:
> KeyError: 'items'
> /opt/git-askpassword.sh
> Git URL:
> 
> Branch name:
> 
> CommitID:
> buildon-w7l0cav,branchName=master,gitURL=https://github.com/smartdevops/SampleStudentProject.git,KUBEMASTER=10.0.0.94,UPLOADPORT=5000
> mv: cannot move '/var/jenkins/jobs/jenkinsfileJob' to '/var/jenkins/jobs/buildon-w7l0cav,branchName=master,gitURL=https://github.com/smartdevops/SampleStudentProject.git,KUBEMASTER=10.0.0.94,UPLOADPORT=5000': No such file or directory
> pod default/buildon-w7l0cav terminated (Error)
>

**Comment by JeyanthiBalakrishnan** [comment]
user access should not be the problem as long as you have directory permissions. As I mentioned in one of the previous comment, below kubectl should give you the console with the logs of jenkins startup. You just have to run this in kube master command-line to ensure your buildon framework is working. Please observer the log in command line execution and not from the framework.log . What is the kubernette version you are using ?

kubectl run '65xlyxk' -i --tty --rm --restart=Never --image='devopsbasservice/buildonframework:buildonJenkinsfile2.0' --env=commitID='65xlyxk',branchName='master',gitURL='https://github.com/smartdevops/SampleStudentProject.git',KUBEMASTER='10.0.0.94',UPLOADPORT='5000'

**Comment by smartdevops** [comment]
Kubernetes v1.8.3.
I have followed the steps for Kubernetes cluster setup from
https://onedevops.atlassian.net/wiki/spaces/OB/pages/11108353/Installation+of+BuildOn

**Comment by JeyanthiBalakrishnan** [comment]
Ah! ok. We have tested buildon with Kubernetes v1.6.x . As you know, apt-get install will always pull the latest kubernetes version. Please check if you can downgrade to v1.6.4 while I check buildon for v1.8.3.

**Comment by smartdevops** [comment]
Jeyanthi,

I have downgraded kubernetes to v1.6.4 and still the buildon doesn't finished.
Here's the logs
[buildon_rollingfile.2017-11-29.0.log](https://github.com/CognizantOneDevOps/BuildOn/files/1513933/buildon_rollingfile.2017-11-29.0.log)
[framework.log](https://github.com/CognizantOneDevOps/BuildOn/files/1513934/framework.log)

**Comment by JeyanthiBalakrishnan** [comment]
As per log, you have 2 exceptions. Kubernets exception and file permission exception.

2017-11-29 13:22:22 [http-nio-8443-exec-6] DEBUG c.c.buildon.domain.GitOperations - io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [default]  failed.
2017-11-29 13:22:22 [http-nio-8443-exec-6] DEBUG c.c.buildon.domain.GitOperations - getDBServiceUpdate:null:mwssmzn:null
2017-11-29 13:22:22 [http-nio-8443-exec-6] DEBUG c.c.buildon.domain.GitOperations - fileName.../root/buildlog/mwssmzn/Jenkinsfilecommitid...mwssmzn
2017-11-29 13:22:22 [http-nio-8443-exec-6] DEBUG c.c.buildon.domain.GitOperations - java.io.FileNotFoundException: /root/buildlog/mwssmzn/Jenkinsfile (Permission denied)
2017-11-29 13:22:22 [http-nio-8443-exec-1] DEBUG c.c.buildon.dao.BuildOnDAOImpl - getEmailForUser: 123123

Did you tried kubectl run command this time after v1.6.4 downgrade ?

**Comment by JeyanthiBalakrishnan** [comment]
I am able to replicate your issue in kubernetes v1.8.3. latest version expecting the --env argument in the below format.

**Solution below:**
  kubectl run '65xlyxk' -i --tty --rm --restart=Never --image='devopsbasservice/buildonframework:buildonJenkinsfile2.0' --env="commitID=65xlyxk" --env="branchName=master" --env="gitURL=https://github.com/smartdevops/SampleStudentProject.git" --env="KUBEMASTER=10.0.0.94" --env="UPLOADPORT=5000" 

Allow anonymous to access kube API. Below steps mentioned in our wiki "Knowledge Base".
https://onedevops.atlassian.net/wiki/spaces/OB/pages/12877861/API+access+issue

 kubectl create rolebinding anonymous --clusterrole=cluster-admin --user=system:anonymous --namespace=default
 
 kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts

 curl -k `(kubectl config view | grep server | cut -f 2- -d ":" | tr -d " ")`/api/v1/namespaces/default/pods/ --header "Authorization: Bearer `(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')`" 

Updated buildon.py with the below line change to support kubernetes v1.8.3 (Refer master branch buildon.py)
subprocess.Popen(['kubectl run '+ self.uid +' -i --tty --rm --restart=Never --image='+imagename+ ' --env="commitID='+self.uid+'" --env="branchName='+self.tuid+'" --env="gitURL='+self.httpurl+'" --env="KUBEMASTER='+self.host_ip+'" --env="UPLOADPORT='+self.upload_port+'"'], shell=True) 

 To resolve permission related issue. Run tomcat8 as the service using root user. 
 Restart tomcat to reflect above kubernetes v1.8.3 changes.

Now, you can revert to kubernetes 1.8.3. You will face an issues in docker if you downgrade kubernetes version alone to v1.6.4. So, you are all set to use latest and openldap with our latest code base.

At this point in time, you are all set to trigger the buildon and should be able to see the result.

**Comment by smartdevops** [comment]
Jeyanthi,
I have upgraded kube to 1.8 and tried to use latest code base from master.
I'm not able to start the python framework.
Attaching the framework logs for your reference 
[framework.log](https://github.com/CognizantOneDevOps/BuildOn/files/1516681/framework.log)

**Comment by JeyanthiBalakrishnan** [comment]
It is an python indentation error. Move the subprocess command indentation parallel to immediate if condition. Just updated in master. Please refer.

**Comment by smartdevops** [comment]
After using the latest buildon.py python framework is up and running. But the buildon is not completed.
I could see the pods are getting created in k8s.

> kubectl get pods
> NAME              READY     STATUS    RESTARTS   AGE
> buildon-eicrguo   1/1       Running   0          59s
> 

Here's the buildon and framework logs
[buildon_rollingfile.2017-11-30.0.log](https://github.com/CognizantOneDevOps/BuildOn/files/1517372/buildon_rollingfile.2017-11-30.0.log)
[framework.log](https://github.com/CognizantOneDevOps/BuildOn/files/1517374/framework.log)

I'm running tomcat8 as a service

**Comment by JeyanthiBalakrishnan** [comment]
Are you able to trigger buildon from UI and see the result in "Individual Build Report" ?

**Comment by smartdevops** [comment]
Individual Build Report page is not displayed. The request is still on Build on Tab

![image](https://user-images.githubusercontent.com/33824782/33427539-9ed4e178-d5eb-11e7-9dbb-868c62b7f7eb.png)

**Comment by JeyanthiBalakrishnan** [comment]
I hope you have restarted tomcat after all the changes. On clicking the "BuildOn", it will call the "python.url". If your python framework is running on port 5000, it should accept call from BuildOn UI.  
I would suggest to verify the python url and connectivity. I assume that you did rebase your code with our BuildOn release v1.2.1.

#Kubernetes
python.url=http://xx.xx.xx.xx:5000
#kube API URL
kubernetes.url=https://xxx.xxx.xx.xx:6443

Also, Clear your browser cache and try again.

**Comment by smartdevops** [comment]
Yes i have restarted tomcat. 
All my properties are set

> #Kubernetes
> python.url=http://10.0.0.94:5000
> kubernetes.url=https://10.0.0.94:6443

>  netstat -tulnp | grep 5000
> tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      8148/python
> 
> 
> netstat -tulnp | grep 6443
> tcp6       0      0 :::6443                 :::*                    LISTEN      5664/kube-apiserver
> 

Pod creation is happening on k8s . I'm attaching the pod logs.
[pod_logs.txt](https://github.com/CognizantOneDevOps/BuildOn/files/1517595/pod_logs.txt)

**Comment by JeyanthiBalakrishnan** [comment]
Do you see any exception in your catalina.out log ? 

By the way, did you execute the below commands in your kubernetes v1.8.3 ?
 
kubectl create rolebinding anonymous --clusterrole=cluster-admin --user=system:anonymous --namespace=default
 
 kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts

 curl -k `(kubectl config view | grep server | cut -f 2- -d ":" | tr -d " ")`/api/v1/namespaces/default/pods/ --header "Authorization: Bearer `(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')`" 

Also, do the hard refresh ClearCache in chrome://settings

**Comment by smartdevops** [comment]
Yes. I have executed the role binding commands as per the documentation.
No error in catalina.out . Found an  exception in localhost log

> 30-Nov-2017 12:21:29.093 SEVERE [http-nio-9090-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [com.cognizant.buildon.controller.BuildonWebController] in context with path [/buildon] threw exception
>  java.lang.NullPointerException
>         at com.cognizant.buildon.domain.GitOperations.callBuildon(GitOperations.java:728)
>         at com.cognizant.buildon.controller.BuildonWebController.doPost(BuildonWebController.java:281)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
>         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
>         at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
>         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.lang.Thread.run(Thread.java:748)
> 

Attaching the logs files 
[catalina.2017-11-30.log](https://github.com/CognizantOneDevOps/BuildOn/files/1517807/catalina.2017-11-30.log)
[localhost.2017-11-30.log](https://github.com/CognizantOneDevOps/BuildOn/files/1517808/localhost.2017-11-30.log)

**Comment by JeyanthiBalakrishnan** [comment]
Below line will create the temporary directory to clone the code under /tmp and will be deleted after buildon trigger.
localPath = File.createTempFile("TestGitRepository", "");

In case, if it is deleted after clone then we will get NullPointerException. In this case, git cloned temporary path value is set null. Add snippet as shown below in GitOperations.java. Then rebuild and deploy.

cloneRepo method:
	**session.setAttribute(Constants.LOCALPATH,localPath);**
	return localPath;

callBuildon method:
               repository.close();
		**if(null!=path){
		File f=new File(path.toString());
		delete(f);
		}**
		return isSuccess;

**Comment by smartdevops** [comment]
Now I can see the build running successfully in pipeline. But the status is still showing as "In progress". Why?

![image](https://user-images.githubusercontent.com/33824782/33477828-25fb1660-d6ad-11e7-9ff4-45c68c5314f4.png)

Logs attached
[buildon_rollingfile.2017-12-01.4.log](https://github.com/CognizantOneDevOps/BuildOn/files/1521166/buildon_rollingfile.2017-12-01.4.log)
[framework.log](https://github.com/CognizantOneDevOps/BuildOn/files/1521167/framework.log)
[localhost.2017-12-01.log](https://github.com/CognizantOneDevOps/BuildOn/files/1521168/localhost.2017-12-01.log)

**Comment by JeyanthiBalakrishnan** [comment]
Check your ip-address and mac address are valid. If your hostname resolving to loopback address 127.0.0.1 then mac address will throw NullPointerException. We have used network interface properties for encryption. Update your /etc/hosts file  that hostname resolve to private ip-address or valid host ip-address.
Please trigger few more BuildOn triggers in your environment and see if issue still persists.  As the original issue BuildOn failing resolved, Closing issue.
