### ISSUE TITLE
Buildon status is inprogress

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#5]
I'm able to run buildon with latest code base and kubernetes 1.8.
The build status is showing as Inprogress
![image](https://user-images.githubusercontent.com/33824782/33482148-ac9c3ffe-d6bd-11e7-9d3f-253b9f548dfa.png)

The DNS is resolving properly

ping ip-10-0-0-94
PING ip-10-0-0-94.ec2.internal (10.0.0.94) 56(84) bytes of data.
64 bytes from ip-10-0-0-94.ec2.internal (10.0.0.94): icmp_seq=1 ttl=64 time=0.030 ms

ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.029 ms

[buildon_rollingfile.2017-12-01.4.log](https://github.com/CognizantOneDevOps/BuildOn/files/1521508/buildon_rollingfile.2017-12-01.4.log)
[framework.log](https://github.com/CognizantOneDevOps/BuildOn/files/1521509/framework.log)
[localhost.2017-12-01.log](https://github.com/CognizantOneDevOps/BuildOn/files/1521510/localhost.2017-12-01.log)

**Comment by JeyanthiBalakrishnan** [comment]
Please validate if the below reference link code returns eth0 ip address and MAC address. If you get Nullpointerexception for MAC address then network interface to be fixed in the instance.

https://www.javascan.com/194/mac-address-in-java-example

Please check and confirm.

**Comment by smartdevops** [comment]
Jeyanthi,

Mac address and NIC doesn't have any problem.

> java JavaMacAddress
> IP address : 10.0.0.94
> MAC address : 0E-EA-5D-E8-85-08

The problem is with the hard-coded postgresql db password in dbupdate.py. 
After updating the password the build on status is success now.
![image](https://user-images.githubusercontent.com/33824782/33537462-98010fe0-d8e1-11e7-94c9-5184eb77729d.png)


Thanks

**Comment by JeyanthiBalakrishnan** [comment]
Glad to hear that issue is resolved. We will externalise PostgreSQL details in next release. Thank you! Closing the issue.
