### ISSUE TITLE
Openldap authentication not working

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#6]
Hi,
I have tried to setup the openldap with latest code base.
But login not succeeded.

> 2017-12-04 12:40:15 [http-nio-8443-exec-6] DEBUG c.m.v.resourcepool.BasicResourcePool - awaitAvailable(): [unknown]
> 2017-12-04 12:40:16 [http-nio-8443-exec-6] DEBUG c.c.b.domain.LDAPAuthentication - javax.naming.NotContextException: Not an instance of DirContext
> 2017-12-04 12:40:27 [DefaultQuartzScheduler_QuartzSchedulerThread] DEBUG o.quartz.core.QuartzSchedulerThread - batch acquisition of 0 triggers
> 

Here's is my LDAP setttings

#LDAP
ldap.server=ldap://ldapserver:389
#For openLDAP anonymous user  ldap.user and ldap.password set to empty.
#For LDAP set values - ldap.user and ldap.password
ldap.user=Manager
ldap.password=password
ldap.searchbase=dc=maxcrc,dc=com
ldap.distributionlist=
#For ldap isLDAP set to true
ldap.isLDAP=true
#For openldap isopenLDAP set to true
ldap.isopenLDAP=true

**Comment by JeyanthiBalakrishnan** [comment]
We will try to replicate the same and will respond.

**Comment by JeyanthiBalakrishnan** [comment]
Issue resolved in v1.2.2 release. Hence, closing issue.
