### ISSUE TITLE
Significance of web-hooks in buildon

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#7]
I tried to turn OFF the web-hook and I can modify the Jenkins file through Jenkinsfile editor and check-in.
When web-hook is turned ON I can commit the Jenkins file through editor. What is the significance of this ON option?Will it trigger build on automatically?

**Comment by SowmiyaRanganathan** [comment]
When Webhook is ON, commit given directly from the framework i.e when commit given from the SCM , BuildOn for that commit gets triggered automatically. (This will call the Python service webhook configured in your repository settings).

When Webhook is OFF - using editor developer can make any number of changes to Jenkinsfile and but can ONLY check-in the code to repository. No BuildOn will be triggered.

But BuildOn will always be triggered when given from UI irrespective of webhook status.

**Comment by smartdevops** [comment]
Sowmiya,

Thanks for the information.
What is the Payload URL for setting up webhook in SCM?
Do you have any documentation on this setup?

**Comment by SowmiyaRanganathan** [comment]
**http://KUBE_MASTER_IP:5000/setup** (Python service running on port 5000)

'setup' is the function in app.py where SCM commit's payload will be delivered.

**Comment by SowmiyaRanganathan** [comment]
Closing.
