### ISSUE TITLE
Pipeline view is not working for buildon triggered from framework

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#9]
Team,

The pipeline view is not working in historical reports for buildon triggered via github webhook framework.

![image](https://user-images.githubusercontent.com/33824782/33831912-f7bffe46-de9f-11e7-8f8f-615b84d13bd5.png)

I have found an exception on tomcat localhost  log

> 11-Dec-2017 12:48:08.420 SEVERE [http-nio-8443-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [com.cognizant.buildon.controller.HistoricCIWebController] in context with path [/buildon] threw exception
>  java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>         at java.util.ArrayList.rangeCheck(ArrayList.java:657)
>         at java.util.ArrayList.get(ArrayList.java:433)
>         at com.cognizant.buildon.domain.GitOperations.gethistoricalBranch(GitOperations.java:1229)
>         at com.cognizant.buildon.controller.HistoricCIWebController.doPost(HistoricCIWebController.java:277)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
>

**Comment by JeyanthiBalakrishnan** [comment]
There is a bug fix on the same to be released as  v1.2.2 by Tomorrow (12.12.2017).

**Comment by JeyanthiBalakrishnan** [comment]
Issue resolved in v1.2.2 release. Hence, closing issue.
